CREATE TABLE TRANSFERENCIAS_DE_CUSTO(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_SOLICITACAO] [int] NOT NULL,
	[CODCOLIGADA_ORIGEM] [int] NOT NULL,
	[CCUSTO_ORIGEM] [varchar](7) NOT NULL,
	[CODCOLIGADA_DESTINO] [int] NOT NULL,
	[CCUSTO_DESTINO] [varchar](7) NOT NULL,
	[SOLICITANTE] [varchar](100) NOT NULL,
	[VALOR] [float] NOT NULL,
	[OBSERVACAO] [varchar](500),
	[DATA_SOLICITACAO] [datetime] NOT NULL,
	[DATA_COMPETENCIA] [date] NULL,
	[STATUS] [int] NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE [dbo].[TRANSFERENCIAS_DE_CUSTO_HISTORICO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TRANSFERENCIA] [int] NULL,
	[USUARIO] [varchar](100) NOT NULL,
	[DATA_HISTORICO] [datetime] NOT NULL,
	[OBSERVACAO] [varchar](200) NOT NULL,
	[DECISAO] [varchar](100) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE TRANSFERENCIAS_DE_CUSTO_HISTORICO  ADD FOREIGN KEY(ID_TRANSFERENCIA) REFERENCES TRANSFERENCIAS_DE_CUSTO (ID);

CREATE TABLE TRANSFERENCIAS_DE_CUSTO_TRANSFERENCIA(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TRANSFERENCIA] [int] NULL,
	[TIPO] [varchar](200) NOT NULL,
	[VALOR] [float] NOT NULL,
	[JUSTIFICATIVA] [varchar](200) NOT NULL,
	[TRANSFERE_CUSTO] [bit] NOT NULL,
	[TRANSFERE_RECEITA] [bit] NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE TRANSFERENCIAS_DE_CUSTO_TRANSFERENCIA  ADD FOREIGN KEY(ID_TRANSFERENCIA) REFERENCES [TRANSFERENCIAS_DE_CUSTO] (ID);

CREATE TABLE TRANSFERENCIAS_DE_CUSTO_ITENS(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TRANSFERENCIA] [int] NULL,
	[CODIGO_PRODUTO] [varchar](200) NOT NULL,
	[DESCRICAO_PRODUTO] [varchar](200) NOT NULL,
	[DESCRICAO] [varchar](200) NOT NULL,
	[QUANTIDADE] [float] NOT NULL,
	[UNIDADE] [varchar](200) NOT NULL,
	[VALOR_UNITARIO] [float] NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE [TRANSFERENCIAS_DE_CUSTO_ITENS]   ADD FOREIGN KEY(ID_TRANSFERENCIA) REFERENCES TRANSFERENCIAS_DE_CUSTO_TRANSFERENCIA (ID);